# ================================================================
#  GLOBAL SKILL LIBRARY — 1000+ Skills
#  Covers: Programming, AI/ML, Cloud, DevOps, Security, Data,
#          Frontend, Backend, Mobile, Blockchain, Game Dev,
#          Embedded, Databases, Tools, Frameworks, Soft Skills
#  Used by: ResumeParser, JobSkillExtractor, ATSEngine
# ================================================================

GLOBAL_SKILLS = [

    # ── PROGRAMMING LANGUAGES ───────────────────────────────
    "Python", "Java", "C", "C++", "C#", "JavaScript", "TypeScript",
    "Go", "Golang", "Rust", "Scala", "Kotlin", "Swift", "Objective-C",
    "R", "MATLAB", "Dart", "PHP", "Ruby", "Perl", "Haskell", "Erlang",
    "Elixir", "Clojure", "F#", "Julia", "Lua", "Groovy", "COBOL",
    "Fortran", "Assembly", "Bash", "Shell", "PowerShell", "Solidity",
    "Move", "Vyper", "Cairo", "Zig", "Nim", "Crystal", "V",
    "PureScript", "Elm", "OCaml", "Prolog", "Lisp",

    # ── WEB FRONTEND ────────────────────────────────────────
    "HTML", "HTML5", "CSS", "CSS3", "SASS", "SCSS", "LESS",
    "Bootstrap", "Tailwind CSS", "Material UI", "Ant Design",
    "Chakra UI", "Shadcn UI", "Bulma", "Foundation",
    "React", "React.js", "Next.js", "Gatsby", "Remix",
    "Angular", "AngularJS", "Vue", "Vue.js", "Nuxt.js",
    "Svelte", "SvelteKit", "Solid.js", "Astro", "Qwik",
    "Redux", "Zustand", "MobX", "Recoil", "Jotai", "Pinia",
    "Webpack", "Vite", "Rollup", "Parcel", "ESBuild", "Turbopack",
    "jQuery", "Alpine.js", "HTMX", "Stimulus",
    "GraphQL", "Apollo Client", "React Query", "TanStack Query",
    "WebSockets", "Socket.io", "Web Workers", "Service Workers",
    "PWA", "WebAssembly", "WASM",
    "Responsive Design", "Cross-browser Compatibility",
    "Web Accessibility", "WCAG", "SEO", "Core Web Vitals",
    "Storybook", "Figma", "Adobe XD", "Sketch", "InVision",

    # ── WEB BACKEND ─────────────────────────────────────────
    "Node.js", "Express.js", "Express", "NestJS", "Fastify", "Koa",
    "Hapi.js", "AdonisJS", "Strapi",
    "Django", "Flask", "FastAPI", "Tornado", "Sanic", "Pyramid",
    "Spring", "Spring Boot", "Spring Security", "Spring MVC",
    "Spring Cloud", "Hibernate", "JPA", "Maven", "Gradle",
    "ASP.NET", "ASP.NET Core", ".NET", ".NET Core", "Entity Framework",
    "Blazor", "SignalR",
    "Laravel", "Symfony", "CodeIgniter", "Lumen",
    "Ruby on Rails", "Sinatra",
    "Gin", "Echo", "Fiber", "Chi",
    "Actix", "Axum", "Rocket",
    "gRPC", "REST API", "RESTful API", "SOAP", "GraphQL API",
    "WebSockets", "Server-Sent Events", "Long Polling",
    "OAuth", "OAuth2", "JWT", "OpenID Connect", "SAML",
    "API Gateway", "Rate Limiting", "API Security",
    "Microservices", "Monolithic Architecture",
    "Event-Driven Architecture", "CQRS", "Event Sourcing",
    "Domain-Driven Design", "DDD", "Hexagonal Architecture",
    "Clean Architecture", "MVC", "MVVM",

    # ── MOBILE DEVELOPMENT ──────────────────────────────────
    "Android", "iOS", "React Native", "Flutter", "Xamarin",
    "SwiftUI", "UIKit", "Jetpack Compose", "Android SDK",
    "Core Data", "Room", "Retrofit", "Alamofire", "Combine",
    "RxSwift", "RxJava", "Dagger", "Hilt",
    "Firebase", "Expo", "Capacitor", "Ionic",
    "App Store Optimization", "Play Store", "Mobile CI/CD",
    "Fastlane", "AppCenter", "TestFlight",
    "Push Notifications", "Deep Linking", "In-App Purchases",
    "Mobile Testing", "XCTest", "Espresso", "Detox",

    # ── DATABASES ───────────────────────────────────────────
    "MySQL", "PostgreSQL", "MariaDB", "SQLite", "Oracle Database",
    "Microsoft SQL Server", "MSSQL", "DB2",
    "MongoDB", "Mongoose", "CouchDB", "CouchBase",
    "Redis", "Memcached", "DynamoDB", "Cassandra", "ScyllaDB",
    "HBase", "Bigtable", "Firestore", "Firebase Realtime Database",
    "Supabase", "PlanetScale", "Neon", "TiDB",
    "Neo4j", "ArangoDB", "Dgraph", "TigerGraph",
    "InfluxDB", "TimescaleDB", "Prometheus", "OpenTSDB",
    "Elasticsearch", "OpenSearch", "Solr", "Typesense", "Meilisearch",
    "Pinecone", "Weaviate", "Qdrant", "Chroma", "Milvus",
    "SQL", "PL/SQL", "T-SQL", "NoSQL", "NewSQL",
    "Database Design", "Schema Design", "Database Normalization",
    "Query Optimization", "Indexing", "Sharding", "Replication",
    "ACID", "CAP Theorem", "Database Migration", "ORM",

    # ── AI / MACHINE LEARNING ───────────────────────────────
    "Machine Learning", "Deep Learning", "Artificial Intelligence",
    "Supervised Learning", "Unsupervised Learning",
    "Semi-supervised Learning", "Self-supervised Learning",
    "Reinforcement Learning", "Transfer Learning",
    "Meta-learning", "Federated Learning", "Online Learning",
    "Natural Language Processing", "NLP", "Text Classification",
    "Sentiment Analysis", "Named Entity Recognition", "NER",
    "Text Summarization", "Machine Translation", "Question Answering",
    "Information Retrieval", "Topic Modeling", "Word Embeddings",
    "BERT", "GPT", "GPT-4", "LLaMA", "Mistral", "Claude",
    "Transformers", "Attention Mechanism", "RLHF",
    "Large Language Models", "LLM", "Generative AI",
    "Prompt Engineering", "Few-shot Learning", "Zero-shot Learning",
    "Chain-of-Thought", "LangChain", "LlamaIndex", "Haystack",
    "RAG", "Retrieval Augmented Generation",
    "Vector Database", "Semantic Search", "Embeddings",
    "Computer Vision", "Image Classification", "Object Detection",
    "Image Segmentation", "Facial Recognition", "OCR",
    "YOLO", "Detectron2", "OpenCV", "PIL", "Pillow",
    "Generative Models", "GANs", "VAE", "Diffusion Models",
    "Stable Diffusion", "DALL-E", "Midjourney",
    "Speech Recognition", "Text-to-Speech", "Audio Processing",
    "Whisper", "Wav2Vec", "DeepSpeech",
    "Recommendation Systems", "Collaborative Filtering",
    "Content-Based Filtering", "Matrix Factorization",
    "Time Series Analysis", "Forecasting", "ARIMA", "Prophet",
    "Anomaly Detection", "Fraud Detection",
    "Feature Engineering", "Feature Selection", "PCA",
    "Dimensionality Reduction", "UMAP", "t-SNE",
    "Model Evaluation", "Cross Validation", "Hyperparameter Tuning",
    "AutoML", "Neural Architecture Search", "Model Compression",
    "Quantization", "Pruning", "Knowledge Distillation",
    "Explainable AI", "XAI", "SHAP", "LIME", "LIME",
    "Causal Inference", "Bayesian Methods", "Probabilistic Programming",
    "A/B Testing", "Statistical Significance",

    # ── ML FRAMEWORKS & TOOLS ───────────────────────────────
    "TensorFlow", "PyTorch", "Keras", "JAX", "Flax", "Haiku",
    "Scikit-learn", "XGBoost", "LightGBM", "CatBoost",
    "Hugging Face", "Transformers Library", "Datasets",
    "Pandas", "NumPy", "SciPy", "Statsmodels",
    "Matplotlib", "Seaborn", "Plotly", "Bokeh", "Altair",
    "OpenAI API", "Anthropic API", "Cohere API", "Replicate",
    "MLflow", "Weights & Biases", "W&B", "Neptune", "Comet ML",
    "DVC", "Data Version Control",
    "ONNX", "TensorRT", "OpenVINO", "Core ML", "TFLite",
    "Ray", "Dask", "Modin", "Vaex",
    "PySpark", "Spark MLlib",

    # ── DATA ENGINEERING ────────────────────────────────────
    "Apache Spark", "Hadoop", "HDFS", "YARN", "MapReduce",
    "Apache Kafka", "Apache Flink", "Apache Beam", "Apache Airflow",
    "Apache Hive", "Apache Pig", "Apache HBase", "Apache Nifi",
    "Apache Iceberg", "Apache Hudi", "Delta Lake",
    "dbt", "DBT", "Great Expectations", "Soda",
    "ETL", "ELT", "Data Pipelines", "Data Ingestion",
    "Data Warehousing", "Data Lake", "Data Lakehouse",
    "Snowflake", "BigQuery", "Redshift", "Databricks",
    "Fivetran", "Airbyte", "Stitch", "Talend",
    "Informatica", "SSIS", "DataStage",
    "Data Modeling", "Star Schema", "Snowflake Schema",
    "Dimensional Modeling", "Data Vault",
    "Kafka Connect", "Kafka Streams", "Schema Registry",
    "Data Quality", "Data Governance", "Data Lineage",
    "Metadata Management", "Data Catalog", "Apache Atlas",
    "Presto", "Trino", "Athena", "Druid",
    "Change Data Capture", "CDC", "Debezium",
    "Data Orchestration", "Luigi", "Prefect", "Dagster", "Mage",

    # ── DATA ANALYTICS & BI ─────────────────────────────────
    "Data Analysis", "Exploratory Data Analysis", "EDA",
    "Business Intelligence", "BI", "Dashboards",
    "Tableau", "Power BI", "Looker", "Metabase", "Grafana",
    "Superset", "Apache Superset", "Redash", "Mode Analytics",
    "Excel", "Microsoft Excel", "Advanced Excel", "VBA", "Macros",
    "Google Sheets", "Google Analytics", "Google Data Studio",
    "Looker Studio", "Mixpanel", "Amplitude", "Segment",
    "DAX", "MDX", "Power Query",
    "KPI Tracking", "Funnel Analysis", "Cohort Analysis",
    "Data Storytelling", "Data Visualization",
    "Business Metrics", "OKRs", "North Star Metric",

    # ── CLOUD PLATFORMS ─────────────────────────────────────
    "AWS", "Amazon Web Services", "Azure", "Microsoft Azure",
    "Google Cloud", "GCP", "Google Cloud Platform",
    "IBM Cloud", "Oracle Cloud", "Alibaba Cloud",
    "DigitalOcean", "Linode", "Vultr", "Hetzner",
    "Heroku", "Render", "Railway", "Fly.io", "Vercel", "Netlify",
    "AWS EC2", "AWS S3", "AWS Lambda", "AWS RDS", "AWS EKS",
    "AWS ECS", "AWS VPC", "AWS IAM", "AWS CloudFormation",
    "AWS CDK", "AWS SAM", "AWS CloudWatch", "AWS SQS", "AWS SNS",
    "AWS API Gateway", "AWS Cognito", "AWS Glue", "AWS EMR",
    "AWS Redshift", "AWS Athena", "AWS SageMaker", "AWS Bedrock",
    "Azure VM", "Azure Functions", "Azure Kubernetes Service",
    "Azure DevOps", "Azure Active Directory", "Azure Blob Storage",
    "Azure SQL", "Azure Cosmos DB", "Azure Service Bus",
    "GKE", "Google Kubernetes Engine", "Cloud Run", "Cloud Functions",
    "BigQuery", "Cloud Storage", "Pub/Sub", "Cloud Spanner",
    "Vertex AI", "Cloud Build", "Cloud Composer",
    "Serverless", "Function as a Service", "FaaS",
    "Cloud Security", "IAM", "Cloud Networking",
    "Multi-cloud", "Hybrid Cloud", "Cloud Migration",
    "Cloud Cost Optimization", "FinOps", "CloudFormation", "Terraform",
    "Pulumi", "CDK", "Crossplane",

    # ── DEVOPS & CI/CD ──────────────────────────────────────
    "DevOps", "Docker", "Docker Compose", "Kubernetes", "K8s",
    "Helm", "Kustomize", "ArgoCD", "Flux", "GitOps",
    "Jenkins", "GitHub Actions", "GitLab CI", "GitLab CI/CD",
    "CircleCI", "Travis CI", "Bamboo", "TeamCity",
    "Spinnaker", "Tekton", "DroneCI", "Concourse",
    "Terraform", "Ansible", "Chef", "Puppet", "SaltStack",
    "Packer", "Vagrant", "Vagrant",
    "CI/CD", "Continuous Integration", "Continuous Deployment",
    "Infrastructure as Code", "IaC",
    "Service Mesh", "Istio", "Linkerd", "Consul",
    "Linux", "Ubuntu", "CentOS", "Debian", "RHEL", "Alpine Linux",
    "Bash", "Shell Scripting", "Zsh", "Fish",
    "Nginx", "Apache", "HAProxy", "Traefik", "Caddy",
    "Load Balancing", "Reverse Proxy", "CDN", "Cloudflare",
    "Monitoring", "Observability", "Prometheus", "Grafana",
    "Datadog", "New Relic", "Dynatrace", "AppDynamics",
    "ELK Stack", "Elasticsearch", "Logstash", "Kibana",
    "Fluentd", "FluentBit", "Loki", "Jaeger", "Zipkin",
    "OpenTelemetry", "Distributed Tracing", "APM",
    "SRE", "Site Reliability Engineering", "On-call",
    "Incident Management", "Postmortem", "SLO", "SLA", "SLI",
    "Chaos Engineering", "Chaos Monkey", "Litmus",
    "Capacity Planning", "Performance Tuning",

    # ── CYBERSECURITY ───────────────────────────────────────
    "Cybersecurity", "Information Security", "InfoSec",
    "Penetration Testing", "Pen Testing", "Ethical Hacking",
    "Red Teaming", "Blue Teaming", "Purple Teaming",
    "Network Security", "Web Application Security",
    "OWASP Top 10", "SQL Injection", "XSS", "CSRF", "SSRF",
    "Cryptography", "PKI", "SSL/TLS", "TLS", "OpenSSL",
    "SIEM", "SOC", "Threat Intelligence", "Threat Hunting",
    "Incident Response", "Digital Forensics", "DFIR",
    "Malware Analysis", "Reverse Engineering",
    "Kali Linux", "Metasploit", "Burp Suite", "Nmap",
    "Wireshark", "Nessus", "OpenVAS", "Nikto",
    "OSINT", "Social Engineering", "Phishing",
    "Zero Trust", "Identity and Access Management",
    "Privileged Access Management", "PAM",
    "SAST", "DAST", "IAST", "SCA", "DevSecOps",
    "Container Security", "Kubernetes Security",
    "Cloud Security", "CSPM", "CWPP",
    "Compliance", "GDPR", "HIPAA", "PCI DSS", "SOC2", "ISO 27001",
    "FedRAMP", "NIST", "CIS Controls",
    "Vulnerability Assessment", "Risk Assessment",
    "Security Architecture", "Zero Day", "CVE",
    "Firewalls", "IDS", "IPS", "WAF", "DLP",
    "VPN", "Tor", "DNS Security",

    # ── BLOCKCHAIN & WEB3 ───────────────────────────────────
    "Blockchain", "Ethereum", "Bitcoin", "Solana", "Polygon",
    "Avalanche", "Cardano", "Polkadot", "Cosmos",
    "Solidity", "Vyper", "Move", "Cairo", "Ink",
    "Smart Contracts", "DeFi", "NFT", "NFTs", "DAO",
    "Web3", "Web3.js", "Ethers.js", "Wagmi", "Viem",
    "Hardhat", "Foundry", "Truffle", "Brownie",
    "IPFS", "Filecoin", "Arweave",
    "The Graph", "Chainlink", "OpenZeppelin",
    "Layer 2", "Rollups", "zkRollups", "Optimistic Rollups",
    "Cross-chain", "Bridges", "Wrapped Tokens",
    "Tokenomics", "DApp", "Decentralized Applications",
    "MetaMask", "WalletConnect", "Rainbow",
    "Smart Contract Auditing", "Formal Verification",

    # ── EMBEDDED SYSTEMS ────────────────────────────────────
    "Embedded Systems", "Microcontrollers", "RTOS", "FreeRTOS",
    "Arduino", "Raspberry Pi", "ESP32", "STM32",
    "ARM", "ARM Cortex", "RISC-V", "AVR", "PIC",
    "UART", "SPI", "I2C", "CAN Bus", "USB", "Ethernet",
    "Bare Metal Programming", "Firmware", "Bootloader",
    "Linux Kernel", "Device Drivers", "DKMS",
    "FPGA", "Verilog", "VHDL", "HLS",
    "AUTOSAR", "ISO 26262", "Functional Safety",
    "Embedded Linux", "Yocto", "Buildroot",
    "PCB Design", "Circuit Design", "Oscilloscope",
    "JTAG", "GDB", "OpenOCD", "Segger JLink",
    "Power Management", "Low Power Design", "RTOS",
    "Real-time Systems", "DMA", "Interrupts",
    "IoT", "Internet of Things", "MQTT", "CoAP",
    "BLE", "Bluetooth Low Energy", "Zigbee", "LoRa", "NFC",
    "Edge Computing", "Edge AI", "TFLite Micro",

    # ── GAME DEVELOPMENT ────────────────────────────────────
    "Unity", "Unreal Engine", "Godot", "GameMaker",
    "C# (Unity)", "C++ (Unreal)", "Blueprints",
    "Game Physics", "Rigidbody", "Collision Detection",
    "3D Modeling", "Blender", "Maya", "3ds Max",
    "Shaders", "HLSL", "GLSL", "SPIR-V",
    "OpenGL", "Vulkan", "DirectX", "Metal",
    "WebGL", "Three.js", "Babylon.js",
    "Game AI", "Behavior Trees", "Pathfinding", "A*",
    "Multiplayer Networking", "Photon", "Mirror",
    "Game Design", "Level Design", "Game Audio",
    "Procedural Generation", "Animation", "Rigging",
    "VR", "AR", "XR", "OpenXR", "SteamVR",
    "Unity HDRP", "Unity URP", "Lumen", "Nanite",

    # ── TESTING & QA ────────────────────────────────────────
    "Testing", "Unit Testing", "Integration Testing",
    "End-to-End Testing", "E2E Testing", "Regression Testing",
    "Performance Testing", "Load Testing", "Stress Testing",
    "Security Testing", "Penetration Testing",
    "Selenium", "Playwright", "Cypress", "Puppeteer",
    "Jest", "Vitest", "Mocha", "Jasmine", "Karma",
    "pytest", "unittest", "nose", "tox",
    "JUnit", "TestNG", "Mockito", "PowerMock",
    "NUnit", "xUnit", "SpecFlow",
    "JMeter", "Gatling", "k6", "Artillery", "Locust",
    "Postman", "Insomnia", "Newman", "REST Assured",
    "BDD", "TDD", "ATDD", "Cucumber", "Gherkin",
    "Pact", "Contract Testing", "Mutation Testing",
    "Code Coverage", "SonarQube", "ESLint", "Pylint",
    "Test Management", "TestRail", "Zephyr",
    "Appium", "XCUITest", "Espresso", "Detox",
    "Chaos Testing", "Fault Injection",

    # ── SYSTEM DESIGN & ARCHITECTURE ────────────────────────
    "System Design", "Distributed Systems", "Scalability",
    "High Availability", "Fault Tolerance", "Resilience",
    "Load Balancing", "Caching", "CDN",
    "Message Queues", "RabbitMQ", "Kafka", "SQS", "NATS",
    "Event-Driven Architecture", "Pub/Sub",
    "Service Mesh", "API Gateway",
    "Database Sharding", "Database Replication",
    "Consistent Hashing", "CAP Theorem", "BASE",
    "Microservices Architecture", "SOA",
    "Serverless Architecture", "Edge Architecture",
    "Data Structures", "Algorithms", "Big O Notation",
    "Design Patterns", "SOLID Principles", "DRY", "KISS",
    "Object-Oriented Programming", "OOP",
    "Functional Programming", "FP", "Reactive Programming",
    "Concurrency", "Parallelism", "Async Programming",
    "Clean Code", "Code Review", "Refactoring",
    "Technical Debt", "Software Architecture",

    # ── TOOLS & PLATFORMS ───────────────────────────────────
    "Git", "GitHub", "GitLab", "Bitbucket", "SVN", "Mercurial",
    "Git Flow", "Trunk Based Development",
    "VS Code", "IntelliJ IDEA", "PyCharm", "WebStorm",
    "Eclipse", "NetBeans", "Xcode", "Android Studio",
    "Visual Studio", "Rider", "CLion", "DataGrip",
    "Vim", "Neovim", "Emacs",
    "Jupyter Notebook", "JupyterLab", "Google Colab",
    "Anaconda", "Conda", "pipenv", "poetry",
    "Linux", "MacOS", "Windows", "WSL",
    "Slack", "Jira", "Confluence", "Notion", "Linear",
    "Trello", "Asana", "Monday.com",
    "Postman", "Insomnia", "Thunder Client",
    "Ngrok", "Localtunnel",
    "Makefile", "CMake", "Bazel", "Buck",

    # ── PRODUCT & AGILE ─────────────────────────────────────
    "Agile", "Scrum", "Kanban", "SAFe", "XP",
    "Sprint Planning", "Retrospectives", "Daily Standup",
    "Product Roadmap", "Product Management", "Product Strategy",
    "User Stories", "Epics", "Backlog Refinement",
    "MVP", "A/B Testing", "Feature Flags",
    "Customer Discovery", "User Research", "UX Research",
    "Stakeholder Management", "Go-to-market Strategy",
    "OKRs", "KPIs", "Metrics", "Product Analytics",
    "Competitive Analysis", "Market Research",
    "Wireframing", "Prototyping", "User Testing",
    "Information Architecture", "User Journey Mapping",
    "Figma", "Adobe XD", "Sketch", "InVision", "Zeplin",

    # ── NETWORKING ──────────────────────────────────────────
    "Networking", "TCP/IP", "UDP", "HTTP", "HTTP/2", "HTTP/3",
    "HTTPS", "TLS", "SSL", "DNS", "DHCP", "ARP",
    "BGP", "OSPF", "EIGRP", "IS-IS", "RIP",
    "VLANs", "VPN", "MPLS", "SD-WAN", "SDN",
    "Firewall", "NAT", "Routing", "Switching",
    "Cisco", "Juniper", "Palo Alto", "Fortinet",
    "Network Automation", "Netmiko", "Napalm", "Nornir",
    "Wireshark", "Nmap", "tcpdump",
    "IPv4", "IPv6", "Subnetting", "CIDR",
    "CDN", "Edge Network", "Anycast",
    "5G", "LTE", "WiFi", "Bluetooth",
    "Software Defined Networking", "Network Virtualization",
    "Zero Trust Networking", "SASE",

    # ── QUANTITATIVE / FINANCE ──────────────────────────────
    "Quantitative Analysis", "Quantitative Finance",
    "Algorithmic Trading", "High-Frequency Trading",
    "Financial Mathematics", "Stochastic Calculus",
    "Black-Scholes", "Monte Carlo Simulation",
    "Risk Management", "VaR", "Greeks", "Derivatives",
    "Options Pricing", "Fixed Income", "Portfolio Optimization",
    "Modern Portfolio Theory", "Factor Models",
    "Time Series", "ARIMA", "GARCH",
    "Bloomberg Terminal", "Reuters Eikon",
    "Python for Finance", "QuantLib",
    "Backtesting", "QuantConnect", "Zipline",
    "RegTech", "Compliance Automation", "AML", "KYC",
    "Payment Processing", "Stripe API", "Plaid API",
    "Open Banking", "PSD2", "ISO 20022",
    "Digital Payments", "Crypto Trading",

    # ── OPERATING SYSTEMS & LOW LEVEL ───────────────────────
    "Operating Systems", "Linux Kernel", "Windows Internals",
    "Process Management", "Thread Management", "Scheduler",
    "Virtual Memory", "Paging", "Memory Management",
    "File Systems", "ext4", "NTFS", "ZFS", "Btrfs",
    "System Calls", "POSIX", "UNIX",
    "Containers", "Namespaces", "cgroups", "chroot",
    "Virtualization", "KVM", "QEMU", "VMware", "VirtualBox",
    "Hypervisors", "Type 1", "Type 2",
    "eBPF", "XDP", "DPDK", "RDMA",
    "Profiling", "perf", "gprof", "Valgrind",
    "Debugging", "GDB", "LLDB", "WinDbg", "strace",
    "Compiler Design", "LLVM", "GCC", "Clang",
    "Linker", "Loader", "ELF", "ABI",

    # ── SOFT SKILLS & PROFESSIONAL ──────────────────────────
    "Communication", "Verbal Communication", "Written Communication",
    "Technical Writing", "Documentation",
    "Teamwork", "Collaboration", "Cross-functional Teams",
    "Problem Solving", "Critical Thinking", "Analytical Thinking",
    "Leadership", "Team Leadership", "People Management",
    "Mentoring", "Coaching", "Knowledge Transfer",
    "Time Management", "Prioritization", "Multitasking",
    "Adaptability", "Flexibility", "Learning Agility",
    "Creativity", "Innovation", "Design Thinking",
    "Presentation Skills", "Public Speaking",
    "Negotiation", "Conflict Resolution",
    "Decision Making", "Judgment", "Strategic Thinking",
    "Customer Focus", "Customer Success",
    "Project Management", "PMP", "Prince2",
    "Risk Management", "Change Management",
    "Emotional Intelligence", "EQ", "Empathy",
    "Remote Work", "Async Communication",
    "Code Review", "Technical Interviewing",
    "Open Source Contribution", "Research Skills",

    # ── CERTIFICATIONS & STANDARDS ──────────────────────────
    "AWS Certified", "AWS Solutions Architect",
    "AWS Developer Associate", "AWS DevOps Engineer",
    "Google Cloud Professional", "GCP Professional Data Engineer",
    "Azure Administrator", "Azure Developer",
    "CKA", "CKAD", "CKS", "Kubernetes Certification",
    "CISSP", "CISM", "CEH", "OSCP", "GPEN", "GCIH",
    "PMP", "Scrum Master", "CSM", "SAFe Agile",
    "Terraform Associate", "HashiCorp Certified",
    "TensorFlow Developer Certificate",
    "Data Science Professional", "IBM Data Science",

    # ── RESEARCH & ACADEMIC ─────────────────────────────────
    "Research", "Academic Research", "Literature Review",
    "Paper Writing", "LaTeX", "Research Methodology",
    "Statistical Analysis", "Hypothesis Testing",
    "Experiment Design", "Benchmarking",
    "NeurIPS", "ICML", "ICLR", "CVPR", "ACL", "EMNLP",
    "Reproducible Research", "Open Science",
    "Grant Writing", "Patent Filing",

    # ── MISCELLANEOUS MODERN SKILLS ─────────────────────────
    "Web Scraping", "BeautifulSoup", "Scrapy", "Playwright",
    "Puppeteer", "Selenium", "Cheerio",
    "Automation", "RPA", "UiPath", "Automation Anywhere",
    "Process Mining", "Celery", "Task Queues",
    "Email Marketing", "Twilio", "SendGrid", "Mailgun",
    "PDF Processing", "pdfplumber", "PyPDF2", "pdf2image",
    "Image Processing", "OCR", "Tesseract",
    "Data Extraction", "Web Crawling", "Data Labeling",
    "Label Studio", "Roboflow", "Scale AI",
    "3D Printing", "CAD", "SolidWorks", "AutoCAD",
    "Robotics", "ROS", "ROS2", "Gazebo",
    "Digital Signal Processing", "FFT", "DSP",
    "Bioinformatics", "Genomics", "BLAST", "BioPython",
    "Geographic Information Systems", "GIS", "QGIS", "ArcGIS",
    "Geospatial Analysis", "PostGIS",
    "Quantum Computing", "Qiskit", "Cirq", "PennyLane",
    "Hardware Description Language", "HDL",
    "Technical Support", "Troubleshooting",
    "System Administration", "SysAdmin",
    "Windows Server", "Active Directory", "Group Policy",
    "VMware vSphere", "Proxmox", "XenServer",
    "Backup & Recovery", "Disaster Recovery", "BCP",
    "ITIL", "ITSM", "ServiceNow", "Zendesk", "Freshdesk",

]

# ── DEDUPLICATE ──────────────────────────────────────────
GLOBAL_SKILLS = list(dict.fromkeys(GLOBAL_SKILLS))  # preserve order, remove dupes

# ── LOWERCASE LOOKUP SET (for fast matching) ─────────────
GLOBAL_SKILLS_LOWER = {skill.lower(): skill for skill in GLOBAL_SKILLS}

# ── COMMON ALIASES MAP ───────────────────────────────────
SKILL_ALIASES = {
    "js":               "JavaScript",
    "ts":               "TypeScript",
    "py":               "Python",
    "ml":               "Machine Learning",
    "dl":               "Deep Learning",
    "ai":               "Artificial Intelligence",
    "nlp":              "Natural Language Processing",
    "cv":               "Computer Vision",
    "rl":               "Reinforcement Learning",
    "k8s":              "Kubernetes",
    "tf":               "TensorFlow",
    "pt":               "PyTorch",
    "sk":               "Scikit-learn",
    "sklearn":          "Scikit-learn",
    "scikit":           "Scikit-learn",
    "node":             "Node.js",
    "nodejs":           "Node.js",
    "react":            "React",
    "reactjs":          "React",
    "vuejs":            "Vue.js",
    "vue":              "Vue.js",
    "next":             "Next.js",
    "nextjs":           "Next.js",
    "angular":          "Angular",
    "angular js":       "Angular",
    "express":          "Express.js",
    "expressjs":        "Express.js",
    "spring":           "Spring Boot",
    "django rest":      "Django",
    "drf":              "Django",
    "postgres":         "PostgreSQL",
    "psql":             "PostgreSQL",
    "mongo":            "MongoDB",
    "elastic":          "Elasticsearch",
    "es":               "Elasticsearch",
    "gpt4":             "GPT-4",
    "chatgpt":          "GPT-4",
    "openai":           "OpenAI API",
    "langchain":        "LangChain",
    "huggingface":      "Hugging Face",
    "hf":               "Hugging Face",
    "xgb":              "XGBoost",
    "lgbm":             "LightGBM",
    "amazon aws":       "AWS",
    "google cloud":     "Google Cloud",
    "gcp":              "Google Cloud",
    "microsoft azure":  "Azure",
    "azure cloud":      "Azure",
    "ci cd":            "CI/CD",
    "cicd":             "CI/CD",
    "devops":           "DevOps",
    "mlops":            "MLOps",
    "llmops":           "LLMOps",
    "rag":              "RAG",
    "rest":             "REST API",
    "restful":          "RESTful API",
    "api":              "REST API",
    "graphql":          "GraphQL",
    "sql server":       "Microsoft SQL Server",
    "mssql":            "Microsoft SQL Server",
    "pb":               "Power BI",
    "powerbi":          "Power BI",
    "oop":              "Object-Oriented Programming",
    "fp":               "Functional Programming",
    "tdd":              "TDD",
    "bdd":              "BDD",
    "e2e":              "End-to-End Testing",
    "unit test":        "Unit Testing",
    "git hub":          "GitHub",
    "git lab":          "GitLab",
    "vs code":          "VS Code",
    "vscode":           "VS Code",
    "jupyter":          "Jupyter Notebook",
    "colab":            "Google Colab",
    "r language":       "R",
    "c sharp":          "C#",
    "c plus plus":      "C++",
    "golang":           "Go",
    "dotnet":           ".NET",
    ".net core":        ".NET Core",
    "iac":              "Infrastructure as Code",
    "react native":     "React Native",
    "rn":               "React Native",
    "ios development":  "iOS",
    "android dev":      "Android",
    "solidity smart":   "Solidity",
    "eth":              "Ethereum",
    "etl pipeline":     "ETL",
    "data pipe":        "Data Pipelines",
    "feature eng":      "Feature Engineering",
    "model deploy":     "Model Deployment",
    "pbi":              "Power BI",
    "vim editor":       "Vim",
    "bash scripting":   "Bash",
    "shell script":     "Shell Scripting",
    "linux admin":      "Linux",
    "sys admin":        "System Administration",
    "sysadmin":         "System Administration",
    "pen test":         "Penetration Testing",
    "pentest":          "Penetration Testing",
    "ethical hack":     "Ethical Hacking",
    "infosec":          "Cybersecurity",
    "information sec":  "Cybersecurity",
    "network sec":      "Network Security",
    "app sec":          "Application Security",
    "websocket":        "WebSockets",
    "micro service":    "Microservices",
    "microservice":     "Microservices",
    "ddd":              "Domain-Driven Design",
    "cqrs":             "CQRS",
    "event sourcing":   "Event Sourcing",
    "kafka broker":     "Apache Kafka",
    "spark job":        "Apache Spark",
    "airflow dag":      "Apache Airflow",
    "dbt model":        "dbt",
    "data warehouse":   "Data Warehousing",
    "data lake":        "Data Lake",
    "snowflake db":     "Snowflake",
    "bigquery":         "BigQuery",
    "redshift":         "Amazon Redshift",
    "arduino uno":      "Arduino",
    "rpi":              "Raspberry Pi",
    "raspi":            "Raspberry Pi",
    "iot device":       "IoT",
    "embedded c":       "C",
    "unity3d":          "Unity",
    "unreal":           "Unreal Engine",
    "selenium test":    "Selenium",
    "playwright test":  "Playwright",
    "cypress test":     "Cypress",
    "jest unit":        "Jest",
    "pytest test":      "pytest",
    "jmeter":           "JMeter",
    "sonarqube":        "SonarQube",
    "postman api":      "Postman",
    "figma design":     "Figma",
    "adobe xd":         "Adobe XD",
    "scrum master":     "Scrum",
    "agile dev":        "Agile",
    "jira board":       "Jira",
    "confluence doc":   "Confluence",
}